### PR TITLE
Support ASGI

### PR DESCRIPTION
**Pull request by sanmai-NL**

### CODE REVIEW

**Comment by sanmai-NL** [comment]
Any idea what's happening with the failed tests?

**Comment by carlio** [comment]
You could try running them locally via tox or directly (https://github.com/PyCQA/pylint-django#tests) to see yourself.

It looks like there's a new error being raised that wasn't being raised before. That's possibly due to a new pylint release (last one was on Nov 19 but I'm not sure if anyone ran tests since then). The test output basically says that `no-name-in-module` is being reported by pylint on those test files which the tests were not expecting, not sure why that is but since your change was small I suspect it is caused from an upstream release or regression.

**Comment by carlio** [comment]
@sanmai-NL Seems like @atodorov's PR will fix this : https://github.com/PyCQA/pylint-django/pull/260

**Comment by carlio** [comment]
@sanmai-NL the previous errors are gone now thanks to #260. Can you run [flake8](https://pypi.org/project/flake8/) on it and fix those couple of formatting warnings? That's the only bit that's complaining now.

**Comment by sanmai-NL** [comment]
@carlio: ready for squashing and merging.

**Comment by carlio** [comment]
@sanmai-NL perfect thank you!

@atodorov do you have a release planned? I'll wait on #259 changes first, just don't want to step on your toes if you are doing anything.

**Comment by atodorov** [comment]
@carlio I wasn't planning anything but I agree with you. Let's wait for #259 and release the 2 changes together. Let me know if you want me to build the new package.

**Comment by WayneLambert** [comment]
Thanks for progressing these changes. Have you got another PyPI release planned shortly @atodorov and @carlio to account for the PRs #258 and #259?

**Pull request merged**
